### ISSUE TITLE
Typo in post

### ISSUE THREAD

**Issue by rpglover64** [sdiehl/cooking-generics#1]
(I couldn't find a better place to report it, and your website repository doesn't seem to have the source file to do a pull request).

Under "Compiler Hooks", "allow us to associate data type with out typeclass" should be "allow us to associate data type with our typeclass".

I'm only bothering to report it because it took me a few seconds to figure it out and it broke my flow.

---

EDIT: Later in the document, you have "Using the -XeriveGeneric extension", which should be "Using the -XDeriveGeneric extension".

**Comment by sdiehl** [comment]
Should be fixed now.
